# Generated by Django 4.2.6 on 2023-11-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
    ]
